default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", ENV["USER"]) %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: taskmanagerdevelopment

test:
  <<: *default
  database: taskmanagertest

production:
  <<: *default
  database: taskmanagerproduction
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
